/*
 * Copyright 2026 convex-kt contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.wynq.convex.codegen

import eu.wynq.convex.core.functions.ConvexFunction
import eu.wynq.convex.core.functions.ConvexValidator
import eu.wynq.convex.core.functions.ConvexValidatorField

/**
 * Emits Kotlin source that reconstructs [ConvexFunction] descriptors.
 *
 * The output is plain Kotlin with no reflection: an object with one `val` per
 * function, each building a descriptor literal. Regenerating produces stable
 * output so the result can be committed and diffed.
 */
public object KotlinSourceGenerator {
    /**
     * Generates a source file.
     *
     * @param packageName the package for the generated file.
     * @param objectName the object that holds the functions.
     * @param functions the descriptors to emit.
     * @return the Kotlin source text.
     */
    public fun generate(
        packageName: String,
        objectName: String,
        functions: List<ConvexFunction>,
    ): String {
        val used = mutableSetOf<String>()
        val body = functions.joinToString("\n\n") { function ->
            val property = uniqueName(identifierFor(function), used)
            buildString {
                append("    /** `${function.path}` (${function.kind.wireName}). */\n")
                append("    public val $property: ConvexFunction = ConvexFunction(\n")
                append("        path = \"${function.path}\",\n")
                append("        kind = ConvexFunctionKind.${function.kind.name},\n")
                append("        args = ${validatorExpression(function.args)},\n")
                append("        returns = ${validatorExpression(function.returns)},\n")
                append("    )")
            }
        }
        return buildString {
            append("// Generated by convex-kt codegen. Do not edit.\n")
            append("package $packageName\n\n")
            append("import eu.wynq.convex.core.functions.ConvexFunction\n")
            append("import eu.wynq.convex.core.functions.ConvexFunctionKind\n")
            append("import eu.wynq.convex.core.functions.ConvexValidator\n")
            append("import eu.wynq.convex.core.functions.ConvexValidatorField\n\n")
            append("public object $objectName {\n")
            append(body)
            append("\n}\n")
        }
    }

    private fun validatorExpression(validator: ConvexValidator?): String = when (validator) {
        null -> "null"
        ConvexValidator.Any -> "ConvexValidator.Any"
        ConvexValidator.Null -> "ConvexValidator.Null"
        ConvexValidator.Boolean -> "ConvexValidator.Boolean"
        ConvexValidator.Float64 -> "ConvexValidator.Float64"
        ConvexValidator.Int64 -> "ConvexValidator.Int64"
        ConvexValidator.Bytes -> "ConvexValidator.Bytes"
        is ConvexValidator.String ->
            validator.description
                ?.let { "ConvexValidator.String(\"${escape(it)}\")" }
                ?: "ConvexValidator.String()"
        is ConvexValidator.Id -> "ConvexValidator.Id(\"${escape(validator.table)}\")"
        is ConvexValidator.Array -> "ConvexValidator.Array(${validatorExpression(validator.element)})"
        is ConvexValidator.Object -> objectExpression(validator)
        is ConvexValidator.Union ->
            "ConvexValidator.Union(listOf(" +
                validator.variants.joinToString(", ") { validatorExpression(it) } + "))"
        is ConvexValidator.Literal ->
            "ConvexValidator.Literal(listOf(" +
                validator.values.joinToString(", ") { "\"${escape(it)}\"" } + "))"
    }

    private fun objectExpression(validator: ConvexValidator.Object): String {
        if (validator.fields.isEmpty()) return "ConvexValidator.Object(emptyMap())"
        val entries = validator.fields.entries.joinToString(",\n            ") { (name, field) ->
            "\"${escape(name)}\" to ${fieldExpression(field)}"
        }
        return "ConvexValidator.Object(\n            mapOf(\n            $entries,\n            ),\n        )"
    }

    private fun fieldExpression(field: ConvexValidatorField): String =
        "ConvexValidatorField(${validatorExpression(field.validator)}, optional = ${field.optional})"

    private fun identifierFor(function: ConvexFunction): String {
        val parts = function.path.split(':', '_', '-', '/').filter { it.isNotBlank() }
        if (parts.isEmpty()) return "function"
        val head = parts.first()
        val rest = parts.drop(1).joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }
        return head + rest
    }

    private fun uniqueName(candidate: String, used: MutableSet<String>): String {
        if (used.add(candidate)) return candidate
        var suffix = 2
        while (!used.add("$candidate$suffix")) suffix++
        return "$candidate$suffix"
    }

    private fun escape(text: String): String =
        text.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")
}
